export enum COMMUNITY_SIZE {
    THORP = 'THORP',
    HAMLET = 'HAMLET',
    VILLAGE = 'VILLAGE',
    SMALL_TOWN = 'SMALL_TOWN',
    LARGE_TOWN = 'LARGE_TOWN',
    SMALL_CITY = 'SMALL_CITY',
    LARGE_CITY = 'LARGE_CITY',
    METROPOLIS = 'METROPOLIS'
}