export enum SHAPE {
    CIRCLE = 'CIRCLE',
    OVAL = 'OVAL',
    ELLIPSE = 'ELLIPSE',
    RECT = 'RECT',
    TRIANGLE = 'TRIANGLE',
    POLY = 'POLY',
    COMPOSITE = 'COMPOSITE',
    TEMPLATE = 'TEMPLATE'
}